name: Tests & Lint
on: [push]
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
          check-latest: true
          cache-dependency-path: go.sum
      - name: Clean Build Caches
        run: make clean
      - name: Build & Lint
        run: make lint
      - name: Test
        run: make test
